# Generated by Django 4.2.7 on 2023-11-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_floor", models.IntegerField(default=1)),
                ("is_door_open", models.BooleanField(default=False)),
                ("in_maintenance", models.BooleanField(default=False)),
                ("direction", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_floor", models.IntegerField(blank=True, null=True)),
                ("current_floor", models.IntegerField(blank=True, null=True)),
                ("destination_floor", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="Elevator_app.elevator",
                    ),
                ),
            ],
        ),
    ]
